---
title: "Lab 5 - Confidence intervals"
author: "Team name"
date: "Date of lab session"
output: 
  html_document: 
    fig_height: 4
    highlight: pygments
    theme: spacelab
---

```{r setup, include=FALSE}
# DO NOT ALTER CODE IN THIS CHUNK
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(cache = TRUE)
library(dplyr)
library(ggplot2)
library(mosaic)
```

* * *

## Lab report

#### Load data:
```{r load-data}
load(url("https://stat.duke.edu/~mc301/data/ames.RData"))
```

#### Set a seed:
```{r set-seed}

```


## Exercises:

#### Exercise 1: 

```{r ex1}

```

#### Exercise 2: 


```{r ex2}

```


#### Exercise 3: 

```{r ex3}

```


#### Exercise 4: 


```{r ex4}

```


#### Exercise 5: 

```{r ex5}

```

#### Exercise 6:

```{r ex6}

```

#### Exercise 7: 

```{r ex7}

```

* * *

## On your own:

#### 1: 


```{r oyo1}

```


#### 2: 

```{r oyo2}

```


## Teamwork report

<!--
For each team member, write their name, whether they attended the lab session, 
whether they were the author for this week, and their contribution to the lab 
report (as a percentage). The percentages should add up to 100.
-->

| Team member             | Attendance | Author   | Contribution % |
|:------------------------|:----------:|:--------:|---------------:|
| Name of member 1        | Yes / No   | Yes / No | 25%            |
| Name of member 2        | Yes / No   | Yes / No | 25%            |
| Name of member 3        | Yes / No   | Yes / No | 25%            |
| Name of member 4        | Yes / No   | Yes / No | 25%            |
| Total                   |            |          | 100%           |